# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.4.0"
Vagrant.configure("2") do |config|

    config.vm.box = 'ubuntu/trusty64'
    config.vm.hostname = "dm.caldentey.org"
    config.vm.network :private_network, ip: "192.168.43.8"
    config.ssh.forward_agent = true

    config.ssh.insert_key = false
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

    config.vm.synced_folder ".", "/vagrant", :nfs => true
    config.vm.provider :virtualbox do |vb|
      vb.name = "DMachine"
      vb.memory = 512
      vb.cpus = 1
    end
end
